apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: product-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Ayrus-kira/flipkart-microservices-devops.git
    targetRevision: main
    path: helm/product-service
  destination:
    server: https://kubernetes.default.svc
    namespace: flipkart
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
